### ISSUE TITLE
Outline differences to DavDroid?

### ISSUE THREAD

**Issue by poVoq** [deependhulla/opensync#1]
Neither here or on your website does it mention the differences between OpenSync and DavDroid.
Maybe a short text about the motivations for forking, the already available differences and the roadmap/vision for this fork would be nice to add?
Thanks!

**Comment by devvv4ever** [comment]
I don't think there is any big intention to make enhancements or differences, and of course no vision. Like DAVdroid every successful FOSS project needs some kind of business model so that it can be maintained, which is good for everyone and helps to keep the project going. Putting just a free copy of it to the Play Store (although DAVdroid is ALREADY made available easily and for free via F-Droid by the main developers) destroys this effort and will greatly weaken the development because the developers can't put much time in it if there is no revenue. DAVdroids code is very complex, it takes months even to understand it and to make enhancements; And it took several thousands of hours of hard work and planning to make it great FOSS software and maintain it. I don't think that deepen dhulla can make any reasonable improvements to DAVdroid (if you look at the number of forks he wouldn't even have time to understand all that code and improve it). It will just slow down or stop the core development. Just writing that everyone should get DAVdroid and donate to the project is ok, but it still destroys potential purchases via the Play Store which is the only revenue of the development team behind DAVdroid. If he wants to support Open Source he should take it out of the Play Store. Deepen Dhulla is of course free to fork it and make additions and provide copies of DAVdroid because it is real Open Source. That's not the point. It just isn't very smart and on a longer thinking not helpful for the life of an open source project to remove the business part of it.

**Comment by guettli** [comment]
@devvv4ever I have the impression that you want to ear money with the work done by other people. 

Please refute my impression.

**Comment by guettli** [comment]
@deependhulla  please provide an answer. Closing the issue does not solve the issue.

**Comment by deependhulla** [comment]
I think my website is not being checked properly before creating issue.
https://deependhulla.com/android-apps/opensync-app

OpenSync is mine personal attempt to make a Android App for CalDAV/CardDAV for NextCloud (Server which I use), again a OpenSource Software. Its still Beta from my side as its some basic changes to orginal code of DavDroid. Would try to find time to add more into this app. This is noway to replace original DavDroid app or compete with them.

its unfortunate I haven't got any time to take this app further.

If you love this app, I would recommend you to support DAVdroid (the original app), please consider donating to DAVdroid or purchasing it.
* Now known as DAVx⁵ https://gitlab.com/bitfireAT/davx5-ose

hope this help to understand.
